services:
  db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin
    ports:
      - "8080:80"

volumes:
  db_data: